server:
  port: 8081
spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/poc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: poc_user
    password: password
  # Spring Data hangs when not set under Spring Boot 2.3.0
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        diaect: org.hibernate.dialect.MySQL8Dialect

# kafka properties
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: spring_batch