spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: poc_user
    password: password
  # Spring Data hangs when not set under Spring Boot 2.3.0
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        diaect: org.hibernate.dialect.MySQL8Dialect
# disable batch auto start
  batch:
    job:
      enabled: false
# database
    initialize-schema: always