server:
  port: 8080
spring:
  application:
    name: data-dump-service
# disable batch auto start
  batch:
    job:
      enabled: false

# kafka properties
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: spring_batch